id = "chipkit"
name = "ChipKit"
version = "0.1.1"
schema_version = 1
authors = ["Ang Li <mail@angme.org>"]
description = "Chip design language support: syntax highlighting and diagnostics for SDC, UPF, CPF, and SKILL."
repository = "https://github.com/Leonui/zed-chipkit"

[language_servers.tclsp]
languages = ["SDC", "UPF", "CPF"]

[grammars.tcl]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-tcl"
commit = "8f11ac7206a54ed11210491cee1e0657e2962c47"

[grammars.sdc]
repository = "https://github.com/Leonui/tree-sitter-sdc"
commit = "a1856ebc47ae0917578e91f0e32affc5a104df63"

[grammars.scheme]
repository = "https://github.com/6cdh/tree-sitter-scheme"
commit = "b5c701148501fa056302827442b5b4956f1edc03"
