name = "Tcl"
grammar = "tcl"
path_suffixes = ["tcl"]
line_comments = ["# "]
tab_size = 2
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
